### ISSUE TITLE
Super Assistant created automatically in OpenAI platform?

### ISSUE THREAD

**Issue by jravenel** [ali-abassi/OpenAI_Assistant_API_Boilerplate#1]
Hi @ali-abassi, 

I've started the project, put the .env info but I named my AI Assistant "AIA Jeremy" instead of "Super Assistant" like suggested in your video in OpenAI interface. 
I runned the main, and when I get back to the OpenAI interface, I see a "Super Assistant" created. 

It means that the AI Assistant I run and I've put the key in .env is not the one used in the terminal chat interface. 
Are you aware of this?

I'll deep dive later on the rest of the project but wanted to share this. Maybe there is a PR to be done to make sure this is cleared?

Thanks.

**Comment by ali-abassi** [comment]
Ahh you're right - fixed it now :) thanks for pointing that out!

**Comment by jravenel** [comment]
ok @ali-abassi thank you. I think it would be great to have next evolutions as PR to have better follow up :)

**Comment by ali-abassi** [comment]
📝👀 ---- learning something new everyday haha will do going forward

**Comment by jravenel** [comment]
@ali-abassi ;) it makes it easier to adopt. I'm currently integrating parts of your work into ABI new version, it's promising, and it can become a graduate evolution of this boilerplate.
